# Generated by Django 3.2.9 on 2021-12-09 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, unique=True)),
                ('short_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SquadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('specialization', models.CharField(max_length=200)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.departamentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('surname', models.CharField(max_length=80)),
                ('patronymic', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.squadmodel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studentmodel',
            constraint=models.UniqueConstraint(fields=('name', 'surname', 'patronymic'), name='unique fio'),
        ),
    ]
