# Generated by Django 3.2.9 on 2021-12-09 05:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='age',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 12, 9, 10, 13, 55, 163703), verbose_name='день рождения'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='name',
            field=models.CharField(max_length=80, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='patronymic',
            field=models.CharField(max_length=80, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.squadmodel', verbose_name='номер взвода'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='surname',
            field=models.CharField(max_length=80, verbose_name='фамилия'),
        ),
    ]
