# Generated by Django 3.2.9 on 2021-12-09 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20211209_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 12, 9, 15, 10, 49, 282631), verbose_name='день рождения'),
        ),
    ]
