# Generated by Django 3.2.9 on 2021-12-16 05:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_studentmodel_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Название')),
                ('short_name', models.CharField(max_length=10, verbose_name='Аббревиатура')),
                ('course', models.IntegerField(verbose_name='Курс')),
                ('hours', models.IntegerField(verbose_name='Количество часов')),
                ('type_exam', models.CharField(choices=[('Z', 'зачёт'), ('O', 'зачёт с оценкой'), ('E', 'экзамен')], max_length=1, verbose_name='Тип экзамена')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'ordering': ['date', 'student'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('rank', models.CharField(choices=[('Ml', 'младший лейтенант'), ('L', 'лейтенант'), ('Sl', 'старший лейтенант'), ('C', 'капитан'), ('M', 'майор'), ('PP', 'подполковник'), ('P', 'полковник')], max_length=2, verbose_name='Звание')),
            ],
            options={
                'ordering': ['surname', 'name', 'patronymic'],
            },
        ),
        migrations.AlterModelOptions(
            name='departamentmodel',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='squadmodel',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='studentmodel',
            options={'ordering': ['surname', 'name', 'patronymic']},
        ),
        migrations.RemoveConstraint(
            model_name='studentmodel',
            name='unique fio',
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 12, 16, 5, 22, 19, 636738, tzinfo=utc), verbose_name='день рождения'),
        ),
        migrations.AddConstraint(
            model_name='studentmodel',
            constraint=models.UniqueConstraint(fields=('name', 'surname', 'patronymic'), name='unique fio student'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.departamentmodel', verbose_name='Кафедра'),
        ),
        migrations.AddField(
            model_name='mark',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.studentmodel', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.departamentmodel', verbose_name='Кафедра'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('name', 'surname', 'patronymic'), name='unique fio teacher'),
        ),
    ]
