# Generated by Django 3.2.9 on 2022-01-02 06:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20211216_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 1, 2, 6, 37, 17, 442136, tzinfo=utc), verbose_name='день рождения'),
        ),
        migrations.CreateModel(
            name='SquadDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.discipline', verbose_name='Дисциплина')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.squadmodel', verbose_name='Взвод')),
            ],
        ),
        migrations.AlterField(
            model_name='mark',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.squaddiscipline', verbose_name='Дисциплина'),
        ),
    ]
