# Generated by Django 3.2.9 on 2022-01-04 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_alter_studentmodel_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=400, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 1, 4, 11, 47, 8, 791295, tzinfo=utc), verbose_name='день рождения'),
        ),
    ]
