# Generated by Django 4.0.1 on 2022-01-08 08:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20220104_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='ball',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 1, 8, 8, 22, 7, 550752, tzinfo=utc), verbose_name='день рождения'),
        ),
    ]
